name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Build website
        run: echo "Website built successfully"

      - name: Deploy to GitHub Pages
        uses: actions/upload-pages-artifact@v2
